# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name edgelist
#' @title Edgelist of weighted graph based on energy landscapes.
#' @param x matrix of the cost of travel.
edgelist <- function(x) {
    .Call(`_parthian_edgelist`, x)
}

