# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edgelist <- function(x) {
    .Call(`_parthian_edgelist`, x)
}

rcpp_hello_world <- function() {
    .Call(`_parthian_rcpp_hello_world`)
}

